=== HAkos2/R3SZY2_XMLGyak/R3SZY2_1005/HA_Dogworld.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="konyvek">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="konyvek" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="cim"/>
                <xs:element type="xs:string" name="szerzo"/>
                  <xs:element name="szereplo" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element type="xs:string" name="nev"/>
                        <xs:element type="xs:string" name="baratja"/>
                        <xs:element type="xs:string" name="szuletett"/>
                        <xs:element type="xs:string" name="jellemzes"/>
                      </xs:sequence>
                  </xs:complexType> 
                </xs:element>
              </xs:sequence>
            <xs:attribute name="isbn" type="xs:string"/> 
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== HAkos2/R3SZY2_XMLGyak/R3SZY2_1005/HA_Dogworld.xml
<?xml version="1.0" encoding="UTF-8"?>

<konyvek xmlns:xs="http://w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="HA_Dogworld.xsd">
    <konyv isbn="08361217462">
        <cim>DogWorld</cim>
        <szerzo>Charles M. Schulz</szerzo>

        <szereplo>
            <nev>Snoopy</nev>
            <baratja>Patty</baratja>
            <szuletett>2010-10-04</szuletett>
            <jellemzes>extroveltalt beagle</jellemzes>
        </szereplo>

        <szereplo>
            <nev>Patty</nev>
            <szuletett>2011-08-22</szuletett>
            <jellemzes>vakmero, leany</jellemzes>
        </szereplo>

    </konyv>
</konyvek>
